# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysql:
    platform: linux/x86_64 # M1チップ対応のため追記
    build: ./db/    #Dockerfileからビルドすることを示す
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d  #コンテナ作成時にsqlを実行する
    image: pomodork_mysql # イメージの名前
    container_name: pomodork_db_server
    environment:
      MYSQL_ROOT_PASSWORD: password   #コンテナ内のMySQLを起動する際のパスワードを設定
    ports:
      - "3306:3306"
    networks:
      - pomodork-network
  
  ridgepole:
    platform: linux/x86_64 # M1チップ対応のため追記
    build: ./ridgepole/
    volumes:
      - ./ridgepole/schemas:/ridgepole/schemas
    image: ridgepole
    container_name: ridgepole
    tty: true
    networks:
      - pomodork-network

networks:
  pomodork-network:
