/*
 * POMODORK Backend API
 *
 * POMODORKのバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteTwitterLinkForm - Twitter連携削除
func DeleteTwitterLinkForm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RegisterTwitterLinkForm - Twitter連携登録
func RegisterTwitterLinkForm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
