/*
 * POMODORK Backend API
 *
 * POMODORKのバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	pomodork_constant "pomodork-backend/constant"
	"pomodork-backend/interface/controller"
	pomodork_error "pomodork-backend/message/error"

	"github.com/gin-gonic/gin"
)

// UserControllerRepositories Controllerのインターフェース群
type UserControllerRepositories struct {
	UserAccountController controller.UserAccountControllerInterface
}

// NewUserControllerRepositories UserControllerRepositoriesの生成
func NewUserControllerRepositories() *UserControllerRepositories {
	controller := new(UserControllerRepositories)
	return controller
}

// UserDelete - ユーザ削除
func (u *UserControllerRepositories) UserDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UserCreate - ユーザ登録
func (u *UserControllerRepositories) UserCreate(c *gin.Context) {
	// Controllerの呼び出し
	ctx := context.Background()
	ctx = context.WithValue(ctx, pomodork_constant.TRANSACTION_ID, c.Request.Header.Get(pomodork_constant.TRANSACTION_ID))
	user_id, err := u.UserAccountController.CreateUser(ctx)
	if err != nil {
		var status int
		var response interface{}
		switch err.(type) {
		case *pomodork_error.DuplicateError,
			*pomodork_error.NotFoundError,
			*pomodork_error.SQLExecError:
			status = http.StatusInternalServerError
			response = ErrorResponse{
				ErrorCode:    "E50001",
				ErrorMessage: "システムエラーが発生しました。",
			}
		}
		c.JSON(status, response)
	}

	// 正常レスポンス
	response := InlineResponse200{
		UserId: user_id,
	}
	c.JSON(http.StatusOK, response)
}

// UserSearch - ユーザ取得
func (u *UserControllerRepositories) UserSearch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ApiUserErrorConverter エラーレスポンス変換
func ApiUserErrorConverter(err error) (int, ErrorResponse) {
	switch err {
	case &pomodork_error.ExistsError{}:
		return http.StatusConflict, ErrorResponse{}
	}
	return http.StatusConflict, ErrorResponse{}
}
