/*
 * POMODORK Backend API
 *
 * POMODORKのバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// RegisterTaskForm - タスク登録
func RegisterTaskForm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SearchTaskActualForm - 実績タスク取得
func SearchTaskActualForm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SearchTaskScheduleForm - 予定日タスク取得
func SearchTaskScheduleForm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateTaskForm - タスク更新
func UpdateTaskForm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
