/*
 * POMODORK Backend API
 *
 * POMODORKのバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2001 struct {

	UserId string `json:"user_id,omitempty"`

	ScheduleDate string `json:"schedule_date,omitempty"`

	Tasks []InlineResponse2001Tasks `json:"tasks,omitempty"`
}
