/*
 * POMODORK Backend API
 *
 * POMODORKのバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type User struct {

	UserId string `json:"user_id,omitempty"`

	MailAddress string `json:"mail_address,omitempty"`

	Password string `json:"password,omitempty"`

	AccountName string `json:"account_name,omitempty"`

	LinkTwitterId string `json:"link_twitter_id,omitempty"`
}
