/*
 * POMODORK Backend API
 *
 * POMODORKのバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Task struct {

	UserId string `json:"user_id,omitempty"`

	ScheduleDate string `json:"schedule_date,omitempty"`

	TaskId string `json:"task_id,omitempty"`

	DeleteFlag string `json:"delete_flag,omitempty"`

	TaskName string `json:"task_name,omitempty"`

	PomodoroNum int32 `json:"pomodoro_num,omitempty"`

	PomodoroTime int32 `json:"pomodoro_time,omitempty"`

	CompletionPomodoroNum int32 `json:"completion_pomodoro_num,omitempty"`

	CompletionDate string `json:"completion_date,omitempty"`

	Memo string `json:"memo,omitempty"`
}
