/*
 * POMODORK Backend API
 *
 * POMODORKのバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TwitterLink struct {

	UserId string `json:"user_id,omitempty"`

	LinkTwitterId string `json:"link_twitter_id,omitempty"`
}
